### ISSUE TITLE
bugfix: rename payload of UserAddRoleMutation and UserRemoveRoleMutation

### ISSUE THREAD

**Issue by MoeHome** [serlo/serlo.org-database-layer#312]
There is user_name and role_name in the payload of UserAddRoleMutation but the API sends username and role. But why didn't the test-pacts fail?

_Originally posted by @MoeHome in https://github.com/serlo/api.serlo.org/pull/686#issuecomment-1177726045_

**Comment by hugotiburtino** [comment]
The test pacts in the CI-CD run against the main branch in api and since there for now there is no example for UserCreateMutation it passed.

In order to test it locally, follow [these instructions](https://github.com/serlo/serlo.org-database-layer/blob/main/README.md#run-contract-tests) (the bad news are: some times it fails locally even when it doesn't in CI-CD🤷‍♂️)

**Comment by hugotiburtino** [comment]
closed via #313
