### ISSUE TITLE
Why does database-layer returns `null` for uuid 136306?

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-database-layer#96]
Investigation: Why does the database layer returns null for https://de.serlo.org/136306? Is this a possible bug? See also https://serlo.slack.com/archives/C020XTRK4C9/p1621948545000500

**Comment by inyono** [comment]
This is intentional. Because of legacy reasons (e.g. creating the uuid before its first revision is saved), we have some entries in the database that don't fulfill some constraints. One example would be a repository without any revision (which shouldn't even be allowed to be created, but is, unfortunately). I'm pretty sure we filter some of those out in the database layer. Similarly: uuids without required children will be considered as non-existing -> null.

**Comment by inyono** [comment]
One possibility would be to make the errors more granular, so that we can handle those cases more gracefully (instead of considering it as 404).

**Comment by kulla** [comment]
Question answered -> I'll close the issue...
